language: go
go: "1.10"
jobs:
  include:
    - stage: test
      script: make test
    - stage: publish
      sudo: required
      services:
      - docker
      script: make docker-publish
stages:
  - test
  - name: publish
    if: branch = master AND type = push
