apiVersion: v1
kind: Service
metadata:
  name: go-function-invoker-debug
  labels:
    app: riff
    component: go-function-invoker
spec:
  type: NodePort
  ports:
  - name: delve
    port: 2345
    nodePort: 30111
    targetPort: 2345
  selector:
    function: echo
